// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Sunton_SquareLine_Project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_text_font(ui_Screen2, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Screen2, 0, LV_PART_MAIN | LV_STATE_USER_4);
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_USER_4);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_USER_4);

    ui_TextArea1 = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_TextArea1, 773);
    lv_obj_set_height(ui_TextArea1, 387);
    lv_obj_set_x(ui_TextArea1, 0);
    lv_obj_set_y(ui_TextArea1, 32);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TextArea1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TextArea1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Debug text goes here");
    lv_obj_set_style_text_color(ui_TextArea1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea1, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_color(ui_TextArea1, lv_color_hex(0xFFFFFF), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea1, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_DebugLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_DebugLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DebugLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DebugLabel, -353);
    lv_obj_set_y(ui_DebugLabel, -219);
    lv_obj_set_align(ui_DebugLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DebugLabel, "Debug");
    lv_obj_set_style_text_font(ui_DebugLabel, &ui_font_MeterFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReturnToScreen1Button = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_ReturnToScreen1Button, 100);
    lv_obj_set_height(ui_ReturnToScreen1Button, 50);
    lv_obj_set_x(ui_ReturnToScreen1Button, 338);
    lv_obj_set_y(ui_ReturnToScreen1Button, -205);
    lv_obj_set_align(ui_ReturnToScreen1Button, LV_ALIGN_CENTER);

    ui_ReturnToScreen1BtnLabel = lv_label_create(ui_ReturnToScreen1Button);
    lv_obj_set_width(ui_ReturnToScreen1BtnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReturnToScreen1BtnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ReturnToScreen1BtnLabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ReturnToScreen1BtnLabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ReturnToScreen1BtnLabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_ReturnToScreen1BtnLabel, "Back");
    lv_obj_set_style_text_color(ui_ReturnToScreen1BtnLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ReturnToScreen1BtnLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ReturnToScreen1BtnLabel, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ReturnToScreen1Button, ui_event_ReturnToScreen1Button, LV_EVENT_ALL, NULL);

}
