// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: Sunton_SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_DebugLabel;
extern void ui_event_ReturnToScreen1Button(lv_event_t * e);
extern lv_obj_t * ui_ReturnToScreen1Button;
extern lv_obj_t * ui_ReturnToScreen1BtnLabel;
extern lv_obj_t * ui_PeakHoldLabel;
extern lv_obj_t * ui_PeakHoldSwitch;
extern void ui_event_PeakHoldSwitch(lv_event_t * e);
extern lv_obj_t * ui_PeakHoldDurationLabel;
extern lv_obj_t * ui_PeakHoldDurationSlider;
extern void ui_event_PeakHoldDurationSlider(lv_event_t * e);
extern lv_obj_t * ui_PepToggleLabel;
extern lv_obj_t * ui_PepToggleSwitch;
extern void ui_event_PepToggleSwitch(lv_event_t * e);
extern lv_obj_t * ui_SMeterAveragingSwitch;
extern void ui_event_SMeterAveragingSwitch(lv_event_t * e);
extern lv_obj_t * ui_RebootButton;
extern void ui_event_RebootButton(lv_event_t * e);
// Transverter offset mix toggle
extern bool ui_get_xvtr_offset_mix_enabled(void);
extern void ui_set_xvtr_offset_mix_enabled(bool enabled);
// Transverter (UIXD) toggle
extern bool ui_get_transverter_enabled(void);
extern void ui_set_transverter_enabled(bool enabled);
// Panel Data (UIDE) toggle
extern bool ui_get_panel_data_enabled(void);
extern void ui_set_panel_data_enabled(bool enabled);

// Macro management
extern void ui_macro_refresh_list(void);
extern void ui_macro_set_cached(uint8_t id, const char *name, const char *cmd);
extern void ui_macro_set_fkey_assignment(uint8_t fkey, uint8_t macro_id);

// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

