// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Sunton_SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_text_font(ui_Screen1, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_USER_4);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_USER_4);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_USER_4);

    ui_SignalPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_SignalPanel, 804);
    lv_obj_set_height(ui_SignalPanel, 171);
    lv_obj_set_x(ui_SignalPanel, 0);
    lv_obj_set_y(ui_SignalPanel, -168);
    lv_obj_set_align(ui_SignalPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SignalPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SignalPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SMeterBar = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_SMeterBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_SMeterBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SMeterBar, 200);
    lv_obj_set_height(ui_SMeterBar, 18);
    lv_obj_set_x(ui_SMeterBar, -243);
    lv_obj_set_y(ui_SMeterBar, -200);
    lv_obj_set_align(ui_SMeterBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SMeterBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SMeterBar, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SMeterBar, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SMeterBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SMeterBar, lv_color_hex(0x2081F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SMeterBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SMeterBar, lv_color_hex(0xAC1717), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SMeterBar, 105, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SMeterBar, 135, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SMeterBar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_SMeterLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SMeterLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SMeterLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SMeterLabel, -361);
    lv_obj_set_y(ui_SMeterLabel, -201);
    lv_obj_set_align(ui_SMeterLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SMeterLabel, "S");
    lv_obj_set_style_text_align(ui_SMeterLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SMeterLabel, &ui_font_MeterFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 346);
    lv_obj_set_y(ui_Switch1, 219);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);


    ui_SwrMeterLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SwrMeterLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SwrMeterLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SwrMeterLabel, -374);
    lv_obj_set_y(ui_SwrMeterLabel, -141);
    lv_obj_set_align(ui_SwrMeterLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SwrMeterLabel, "SWR");
    lv_obj_set_style_text_align(ui_SwrMeterLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SwrMeterLabel, &ui_font_MeterFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwrMeterBar = lv_bar_create(ui_Screen1);
    lv_bar_set_mode(ui_SwrMeterBar, LV_BAR_MODE_RANGE);
    lv_bar_set_value(ui_SwrMeterBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_SwrMeterBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SwrMeterBar, 200);
    lv_obj_set_height(ui_SwrMeterBar, 18);
    lv_obj_set_x(ui_SwrMeterBar, -243);
    lv_obj_set_y(ui_SwrMeterBar, -142);
    lv_obj_set_align(ui_SwrMeterBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SwrMeterBar, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_radius(ui_SwrMeterBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SwrMeterBar, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwrMeterBar, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SwrMeterBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SwrMeterBar, lv_color_hex(0x2082F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwrMeterBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SwrMeterBar, lv_color_hex(0x7F2525), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SwrMeterBar, 140, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SwrMeterBar, 160, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SwrMeterBar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_SwrTextLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SwrTextLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SwrTextLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SwrTextLabel, -242);
    lv_obj_set_y(ui_SwrTextLabel, -112);
    lv_obj_set_align(ui_SwrTextLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SwrTextLabel, "1   1.5    2     3        5      ∞");
    lv_obj_set_style_text_font(ui_SwrTextLabel, &ui_font_MeterFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SignalStrengthLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SignalStrengthLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SignalStrengthLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SignalStrengthLabel, -216);
    lv_obj_set_y(ui_SignalStrengthLabel, -225);
    lv_obj_set_align(ui_SignalStrengthLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SignalStrengthLabel, "1  3  5  7  9   +20   +40   +60dB");
    lv_obj_clear_flag(ui_SignalStrengthLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_SignalStrengthLabel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_font(ui_SignalStrengthLabel, &ui_font_MeterFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlcMeterBar = lv_bar_create(ui_Screen1);
    lv_bar_set_mode(ui_AlcMeterBar, LV_BAR_MODE_RANGE);
    lv_bar_set_value(ui_AlcMeterBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_AlcMeterBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_AlcMeterBar, 200);
    lv_obj_set_height(ui_AlcMeterBar, 18);
    lv_obj_set_x(ui_AlcMeterBar, -243);
    lv_obj_set_y(ui_AlcMeterBar, -171);
    lv_obj_set_align(ui_AlcMeterBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_AlcMeterBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AlcMeterBar, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AlcMeterBar, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_AlcMeterBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AlcMeterBar, lv_color_hex(0x2082F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AlcMeterBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_AlcMeterBar, lv_color_hex(0x7F2525), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_AlcMeterBar, 140, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_AlcMeterBar, 160, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_AlcMeterBar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ALC = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ALC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ALC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ALC, -373);
    lv_obj_set_y(ui_ALC, -171);
    lv_obj_set_align(ui_ALC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ALC, "ALC");
    lv_obj_set_style_text_align(ui_ALC, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ALC, &ui_font_MeterFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AfGainBar = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_AfGainBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_AfGainBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_AfGainBar, 105);
    lv_obj_set_height(ui_AfGainBar, 10);
    lv_obj_set_x(ui_AfGainBar, 341);
    lv_obj_set_y(ui_AfGainBar, -128);
    lv_obj_set_align(ui_AfGainBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_AfGainBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_AfGainBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_AfGainLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AfGainLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AfGainLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AfGainLabel, 269);
    lv_obj_set_y(ui_AfGainLabel, -129);
    lv_obj_set_align(ui_AfGainLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AfGainLabel, "AF");
    lv_obj_set_style_text_font(ui_AfGainLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RfGainLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RfGainLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RfGainLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RfGainLabel, 269);
    lv_obj_set_y(ui_RfGainLabel, -108);
    lv_obj_set_align(ui_RfGainLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RfGainLabel, "RF");
    lv_obj_set_style_text_font(ui_RfGainLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RfGainBar = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_RfGainBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_RfGainBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_RfGainBar, 105);
    lv_obj_set_height(ui_RfGainBar, 10);
    lv_obj_set_x(ui_RfGainBar, 341);
    lv_obj_set_y(ui_RfGainBar, -109);
    lv_obj_set_align(ui_RfGainBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_RfGainBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_RfGainBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_VfoAValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_VfoAValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VfoAValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VfoAValue, 0);
    lv_obj_set_y(ui_VfoAValue, 30);
    lv_obj_set_align(ui_VfoAValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VfoAValue, "14.012.000");
    lv_obj_set_style_text_align(ui_VfoAValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VfoAValue, &ui_font_Frequency, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ModeDropDown = lv_dropdown_create(ui_Screen1);
    lv_dropdown_set_dir(ui_ModeDropDown, LV_DIR_RIGHT);
    lv_dropdown_set_options(ui_ModeDropDown, "USB\nLSB\nCW\nDATA\nFM\nAM");
    lv_dropdown_set_selected_highlight(ui_ModeDropDown, false);
    lv_obj_set_width(ui_ModeDropDown, 70);
    lv_obj_set_height(ui_ModeDropDown, 45);
    lv_obj_set_x(ui_ModeDropDown, -121);
    lv_obj_set_y(ui_ModeDropDown, -50);
    lv_obj_set_align(ui_ModeDropDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ModeDropDown, LV_OBJ_FLAG_SCROLL_WITH_ARROW | LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_ModeDropDown, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_ModeDropDown, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_align(ui_ModeDropDown, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ModeDropDown, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ModeDropDown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ModeDropDown, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ModeDropDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ModeDropDown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ModeDropDown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ModeDropDown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ModeDropDown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_ModeDropDown, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ModeDropDown, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(lv_dropdown_get_list(ui_ModeDropDown), LV_TEXT_ALIGN_LEFT,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_ModeDropDown), &ui_font_Font18,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(lv_dropdown_get_list(ui_ModeDropDown), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(lv_dropdown_get_list(ui_ModeDropDown), LV_TEXT_ALIGN_RIGHT,
                                LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_ModeDropDown), &ui_font_Font18,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(lv_dropdown_get_list(ui_ModeDropDown), 0,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_VfoBValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_VfoBValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VfoBValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VfoBValue, 0);
    lv_obj_set_y(ui_VfoBValue, 118);
    lv_obj_set_align(ui_VfoBValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VfoBValue, "14.014.100");
    lv_obj_set_style_text_align(ui_VfoBValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VfoBValue, &ui_font_Font48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VfoAButtonBackground = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_VfoAButtonBackground, 50);
    lv_obj_set_height(ui_VfoAButtonBackground, 50);
    lv_obj_set_x(ui_VfoAButtonBackground, 279);
    lv_obj_set_y(ui_VfoAButtonBackground, 24);
    lv_obj_set_align(ui_VfoAButtonBackground, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_VfoAButtonBackground,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_VfoAButtonBackground, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_VfoAButtonBackground, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VfoALabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_VfoALabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VfoALabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VfoALabel, 279);
    lv_obj_set_y(ui_VfoALabel, 23);
    lv_obj_set_align(ui_VfoALabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VfoALabel, "A");
    lv_obj_set_style_text_align(ui_VfoALabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VfoALabel, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_VfoALabel, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_VfoALabel, lv_color_hex(0x1A92F7), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_VfoALabel, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_VfoALabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_VfoALabel, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_radius(ui_VfoALabel, 0, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_VfoALabel, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_VfoALabel, 255, LV_PART_MAIN | LV_STATE_USER_1);

    ui_VfoBButtonBackground = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_VfoBButtonBackground, 50);
    lv_obj_set_height(ui_VfoBButtonBackground, 50);
    lv_obj_set_x(ui_VfoBButtonBackground, 279);
    lv_obj_set_y(ui_VfoBButtonBackground, 90);
    lv_obj_set_align(ui_VfoBButtonBackground, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VfoBButtonBackground, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_VfoBButtonBackground,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_VfoBButtonBackground, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_VfoBButtonBackground, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_VfoBButtonBackground, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_VfoBButtonBackground, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_VfoBButtonBackground, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_VfoBButtonBackground, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_VfoBButtonBackground, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_VfoBButtonBackground, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_VfoBLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_VfoBLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VfoBLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VfoBLabel, 279);
    lv_obj_set_y(ui_VfoBLabel, 89);
    lv_obj_set_align(ui_VfoBLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VfoBLabel, "B");
    lv_obj_add_flag(ui_VfoBLabel, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_VfoBLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VfoBLabel, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AntButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_AntButton, 70);
    lv_obj_set_height(ui_AntButton, 45);
    lv_obj_set_x(ui_AntButton, -204);
    lv_obj_set_y(ui_AntButton, -50);
    lv_obj_set_align(ui_AntButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AntButton, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AntButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AntButton, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_AntButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ant1Label = lv_label_create(ui_AntButton);
    lv_obj_set_width(ui_Ant1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ant1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Ant1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ant1Label, "ANT 1");
    lv_obj_clear_flag(ui_Ant1Label, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Ant1Label, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ant1Label, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ant2Label = lv_label_create(ui_AntButton);
    lv_obj_set_width(ui_Ant2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ant2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ant2Label, -1);
    lv_obj_set_y(ui_Ant2Label, 0);
    lv_obj_set_align(ui_Ant2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ant2Label, "ANT 2");
    lv_obj_add_flag(ui_Ant2Label, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Ant2Label, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Ant2Label, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ant2Label, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UtcTime = lv_label_create(ui_Screen1);
    //ui_UtcTime = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_UtcTime, 262);
    lv_obj_set_height(ui_UtcTime, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_UtcTime, 81);
    lv_obj_set_y(ui_UtcTime, -195);
    lv_obj_set_align(ui_UtcTime, LV_ALIGN_CENTER);
    // if (strlen("0123456789:") == 0) lv_textarea_set_accepted_chars(ui_UtcTime, NULL);
    // else lv_textarea_set_accepted_chars(ui_UtcTime, "0123456789:");
    lv_label_set_text(ui_UtcTime, "18:20:30");
    lv_obj_clear_flag(ui_UtcTime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_UtcTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UtcTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_UtcTime, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UtcTime, &ui_font_UTCTime, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_UtcTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UtcTime, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UtcTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_UtcTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_UtcTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_UtcTime, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UtcTime, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_UtcTime, LV_TEXT_ALIGN_LEFT, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_UtcTime, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UtcTime, lv_color_hex(0x292831), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UtcTime, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_UtcTime, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_UtcTime, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_UtcTime, lv_color_hex(0x000000), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_UtcTime, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_UtcTime, lv_color_hex(0xFFFFFF), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UtcTime, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_UtcTime, LV_TEXT_ALIGN_LEFT, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UtcTime, &ui_font_UTCTime, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_PwrLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PwrLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PwrLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PwrLabel, -376);
    lv_obj_set_y(ui_PwrLabel, -201);
    lv_obj_set_align(ui_PwrLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PwrLabel, "PWR");
    lv_obj_add_flag(ui_PwrLabel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PwrLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_PwrLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PwrLabel, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PwrValueLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PwrValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PwrValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PwrValueLabel, -236);
    lv_obj_set_y(ui_PwrValueLabel, -225);
    lv_obj_set_align(ui_PwrValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PwrValueLabel, "---10---25---50-----100W");
    lv_obj_add_flag(ui_PwrValueLabel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_PwrValueLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PwrValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PwrValueLabel, &ui_font_MeterFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IfFilter = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_IfFilter, lv_pct(7));
    lv_obj_set_height(ui_IfFilter, lv_pct(6));
    lv_obj_set_x(ui_IfFilter, 202);
    lv_obj_set_y(ui_IfFilter, -50);
    lv_obj_set_align(ui_IfFilter, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_IfFilter, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_IfFilter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IfFilterALabel = lv_label_create(ui_IfFilter);
    lv_obj_set_width(ui_IfFilterALabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IfFilterALabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_IfFilterALabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IfFilterALabel, "FIL A");
    lv_obj_clear_flag(ui_IfFilterALabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_IfFilterALabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IfFilterBLabel = lv_label_create(ui_IfFilter);
    lv_obj_set_width(ui_IfFilterBLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IfFilterBLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_IfFilterBLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IfFilterBLabel, "FIL B");
    lv_obj_add_flag(ui_IfFilterBLabel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_IfFilterBLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_IfFilterBLabel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_align(ui_IfFilterBLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IfFilterBLabel, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RxTxLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RxTxLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RxTxLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RxTxLabel, -380);
    lv_obj_set_y(ui_RxTxLabel, -113);
    lv_obj_set_align(ui_RxTxLabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RxTxLabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_RxTxLabel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_RxTxLabel, "RX");
    lv_obj_add_flag(ui_RxTxLabel, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_RxTxLabel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_RxTxLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RxTxLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RxTxLabel, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RxTxLabel, lv_color_hex(0x2B9B25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RxTxLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_RxTxLabel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RxTxLabel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RxTxLabel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RxTxLabel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_RxTxLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_RxTxLabel, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_font(ui_RxTxLabel, &ui_font_Font16, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_RxTxLabel, lv_color_hex(0xD90202), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_RxTxLabel, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_pad_left(ui_RxTxLabel, 1, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_pad_right(ui_RxTxLabel, 1, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_pad_top(ui_RxTxLabel, 1, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_pad_bottom(ui_RxTxLabel, 1, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PreAmpButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_PreAmpButton, 70);
    lv_obj_set_height(ui_PreAmpButton, 40);
    lv_obj_set_x(ui_PreAmpButton, -360);
    lv_obj_set_y(ui_PreAmpButton, 47);
    lv_obj_set_align(ui_PreAmpButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PreAmpButton, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PreAmpButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_PreAmpButton, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_PreAmpButton, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_PreAmpButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PreAmpButton, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PreAmpButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PreAmpButton, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_PreAmpButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PreAmpButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_radius(ui_PreAmpButton, 0, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_PreAmpButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_PreAmpButton, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    ui_PreAmpButtonLabel = lv_label_create(ui_PreAmpButton);
    lv_obj_set_width(ui_PreAmpButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PreAmpButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PreAmpButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PreAmpButtonLabel, "PRE");
    lv_obj_clear_flag(ui_PreAmpButtonLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_PreAmpButtonLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PreAmpButtonLabel, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AttButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_AttButton, 70);
    lv_obj_set_height(ui_AttButton, 40);
    lv_obj_set_x(ui_AttButton, -360);
    lv_obj_set_y(ui_AttButton, 206);
    lv_obj_set_align(ui_AttButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AttButton, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_AttButton, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_AttButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AttButton, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AttButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_AttButton, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_AttButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_AttButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_radius(ui_AttButton, 0, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_AttButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_AttButton, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    ui_AttButtonLabel = lv_label_create(ui_AttButton);
    lv_obj_set_width(ui_AttButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AttButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AttButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AttButtonLabel, "ATT");
    lv_obj_clear_flag(ui_AttButtonLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_AttButtonLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AttButtonLabel, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AtTuneButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_AtTuneButton, 70);
    lv_obj_set_height(ui_AtTuneButton, 40);
    lv_obj_set_x(ui_AtTuneButton, -360);
    lv_obj_set_y(ui_AtTuneButton, 153);
    lv_obj_set_align(ui_AtTuneButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AtTuneButton, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_AtTuneButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_AtTuneButton, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_AtTuneButton, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_AtTuneButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AtTuneButton, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AtTuneButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_AtTuneButton, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_AtTuneButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_AtTuneButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_radius(ui_AtTuneButton, 0, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_AtTuneButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_AtTuneButton, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    ui_AtTuneButtonLabel = lv_label_create(ui_AtTuneButton);
    lv_obj_set_width(ui_AtTuneButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AtTuneButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AtTuneButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AtTuneButtonLabel, "AT");
    lv_obj_clear_flag(ui_AtTuneButtonLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_AtTuneButtonLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AtTuneButtonLabel, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProcButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ProcButton, 70);
    lv_obj_set_height(ui_ProcButton, 40);
    lv_obj_set_x(ui_ProcButton, -360);
    lv_obj_set_y(ui_ProcButton, 100);
    lv_obj_set_align(ui_ProcButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ProcButton, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ProcButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_ProcButton, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_ProcButton, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_ProcButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProcButton, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProcButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ProcButton, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_ProcButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ProcButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_radius(ui_ProcButton, 0, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_ProcButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ProcButton, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    ui_ProcButtonLabel = lv_label_create(ui_ProcButton);
    lv_obj_set_width(ui_ProcButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProcButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ProcButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProcButtonLabel, "PROC");
    lv_obj_clear_flag(ui_ProcButtonLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_ProcButtonLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProcButtonLabel, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IncreaseSwrButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_IncreaseSwrButton, 78);
    lv_obj_set_height(ui_IncreaseSwrButton, 37);
    lv_obj_set_x(ui_IncreaseSwrButton, -226);
    lv_obj_set_y(ui_IncreaseSwrButton, 211);
    lv_obj_set_align(ui_IncreaseSwrButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IncreaseSwrButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_IncreaseSwrButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_IncreaseSwrButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IncreaseSwrButton, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IncreaseSwrLabel = lv_label_create(ui_IncreaseSwrButton);
    lv_obj_set_width(ui_IncreaseSwrLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IncreaseSwrLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IncreaseSwrLabel, 0);
    lv_obj_set_y(ui_IncreaseSwrLabel, -1);
    lv_obj_set_align(ui_IncreaseSwrLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IncreaseSwrLabel, "INC SWR");
    lv_label_set_recolor(ui_IncreaseSwrLabel, "true");

    ui_DecreaseSwrButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_DecreaseSwrButton, 78);
    lv_obj_set_height(ui_DecreaseSwrButton, 37);
    lv_obj_set_x(ui_DecreaseSwrButton, -138);
    lv_obj_set_y(ui_DecreaseSwrButton, 210);
    lv_obj_set_align(ui_DecreaseSwrButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DecreaseSwrButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DecreaseSwrButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DecreaseSwrButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DecreaseSwrLabel = lv_label_create(ui_DecreaseSwrButton);
    lv_obj_set_width(ui_DecreaseSwrLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DecreaseSwrLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DecreaseSwrLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DecreaseSwrLabel, "DEC SWR");
    lv_obj_set_style_text_font(ui_DecreaseSwrLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IncreaseSMeterButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_IncreaseSMeterButton, 78);
    lv_obj_set_height(ui_IncreaseSMeterButton, 37);
    lv_obj_set_x(ui_IncreaseSMeterButton, -50);
    lv_obj_set_y(ui_IncreaseSMeterButton, 210);
    lv_obj_set_align(ui_IncreaseSMeterButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IncreaseSMeterButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_IncreaseSMeterButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_IncreaseSMeterButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IncreaseSMeterLabel = lv_label_create(ui_IncreaseSMeterButton);
    lv_obj_set_width(ui_IncreaseSMeterLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IncreaseSMeterLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_IncreaseSMeterLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IncreaseSMeterLabel, "INC SM");
    lv_obj_set_style_text_font(ui_IncreaseSMeterLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DecreaseSMeterButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_DecreaseSMeterButton, 78);
    lv_obj_set_height(ui_DecreaseSMeterButton, 37);
    lv_obj_set_x(ui_DecreaseSMeterButton, 40);
    lv_obj_set_y(ui_DecreaseSMeterButton, 210);
    lv_obj_set_align(ui_DecreaseSMeterButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DecreaseSMeterButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DecreaseSMeterButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DecreaseSMeterButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DecreaseSMeterLabel = lv_label_create(ui_DecreaseSMeterButton);
    lv_obj_set_width(ui_DecreaseSMeterLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DecreaseSMeterLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DecreaseSMeterLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DecreaseSMeterLabel, "DEC SM");
    lv_obj_set_style_text_font(ui_DecreaseSMeterLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SplitButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_SplitButton, 70);
    lv_obj_set_height(ui_SplitButton, 45);
    lv_obj_set_x(ui_SplitButton, -39);
    lv_obj_set_y(ui_SplitButton, -50);
    lv_obj_set_align(ui_SplitButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SplitButton, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_SplitButton, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_SplitButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SplitButton, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SplitButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_SplitButton, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_SplitButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SplitButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_radius(ui_SplitButton, 0, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_SplitButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_SplitButton, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    ui_SplitButtonLabel = lv_label_create(ui_SplitButton);
    lv_obj_set_width(ui_SplitButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SplitButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SplitButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SplitButtonLabel, "SPL");
    lv_obj_clear_flag(ui_SplitButtonLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_SplitButtonLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SplitButtonLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_SplitButtonLabel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_NrButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_NrButton, 70);
    lv_obj_set_height(ui_NrButton, 40);
    lv_obj_set_x(ui_NrButton, -360);
    lv_obj_set_y(ui_NrButton, -56);
    lv_obj_set_align(ui_NrButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_NrButton, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_NrButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_NrButton, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_NrButton, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_NrButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NrButton, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NrButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_NrButton, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_NrButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_NrButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_radius(ui_NrButton, 0, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_NrButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_NrButton, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    ui_NrButtonLabel = lv_label_create(ui_NrButton);
    lv_obj_set_width(ui_NrButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NrButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NrButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NrButtonLabel, "NR");
    lv_obj_clear_flag(ui_NrButtonLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_NrButtonLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NrButtonLabel, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AgcLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AgcLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AgcLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AgcLabel, 86);
    lv_obj_set_y(ui_AgcLabel, -50);
    lv_obj_set_align(ui_AgcLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AgcLabel, "AGC-M");
    lv_obj_set_style_text_font(ui_AgcLabel, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RitLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RitLabel, 125);
    lv_obj_set_height(ui_RitLabel, 18);
    lv_obj_set_x(ui_RitLabel, 371);
    lv_obj_set_y(ui_RitLabel, -64);
    lv_obj_set_align(ui_RitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RitLabel, "RIT");
    lv_obj_set_style_text_align(ui_RitLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RitLabel, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RitValue = lv_label_create(ui_RitLabel);
    lv_obj_set_width(ui_RitValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RitValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RitValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RitValue, "0.000");

    ui_XitLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_XitLabel, 125);
    lv_obj_set_height(ui_XitLabel, 18);
    lv_obj_set_x(ui_XitLabel, 371);
    lv_obj_set_y(ui_XitLabel, -44);
    lv_obj_set_align(ui_XitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_XitLabel, "XIT");
    lv_obj_set_style_text_align(ui_XitLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_XitLabel, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RitValue1 = lv_label_create(ui_XitLabel);
    lv_obj_set_width(ui_RitValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RitValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RitValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RitValue1, "0.000");

    ui_PwrSwitch = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_PwrSwitch, 50);
    lv_obj_set_height(ui_PwrSwitch, 25);
    lv_obj_set_x(ui_PwrSwitch, 351);
    lv_obj_set_y(ui_PwrSwitch, -205);
    lv_obj_set_align(ui_PwrSwitch, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PwrSwitch, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_bg_color(ui_PwrSwitch, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PwrSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PwrSwitch, lv_color_hex(0x2B9B25), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PwrSwitch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_OnOffLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_OnOffLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffLabel, 294);
    lv_obj_set_y(ui_OnOffLabel, -205);
    lv_obj_set_align(ui_OnOffLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffLabel, "PWR");
    lv_obj_set_style_text_font(ui_OnOffLabel, &ui_font_MeterFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NbButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_NbButton, 70);
    lv_obj_set_height(ui_NbButton, 40);
    lv_obj_set_x(ui_NbButton, -360);
    lv_obj_set_y(ui_NbButton, -6);
    lv_obj_set_align(ui_NbButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_NbButton, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_NbButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_NbButton, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_NbButton, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_NbButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NbButton, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NbButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_NbButton, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_NbButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_NbButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_radius(ui_NbButton, 0, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_NbButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_NbButton, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    ui_NbButtonLabel = lv_label_create(ui_NbButton);
    lv_obj_set_width(ui_NbButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NbButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NbButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NbButtonLabel, "NB ");
    lv_obj_clear_flag(ui_NbButtonLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_NbButtonLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NbButtonLabel, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DebugMode = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_DebugMode, 78);
    lv_obj_set_height(ui_DebugMode, 37);
    lv_obj_set_x(ui_DebugMode, 347);
    lv_obj_set_y(ui_DebugMode, 167);
    lv_obj_set_align(ui_DebugMode, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DebugMode, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DebugMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DebugMode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DebugMode, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DebugModeButtonLabel = lv_label_create(ui_DebugMode);
    lv_obj_set_width(ui_DebugModeButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DebugModeButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DebugModeButtonLabel, 0);
    lv_obj_set_y(ui_DebugModeButtonLabel, -1);
    lv_obj_set_align(ui_DebugModeButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DebugModeButtonLabel, "DEBUG");
    lv_label_set_recolor(ui_DebugModeButtonLabel, "true");

    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ModeDropDown, ui_event_ModeDropDown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AntButton, ui_event_AntButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_UtcTime, ui_event_UtcTime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IfFilter, ui_event_IfFilter, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RxTxLabel, ui_event_RxTxLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PreAmpButton, ui_event_PreAmpButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AttButton, ui_event_AttButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AtTuneButton, ui_event_AtTuneButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ProcButton, ui_event_ProcButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IncreaseSwrLabel, ui_event_IncreaseSwrLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IncreaseSwrButton, ui_event_IncreaseSwrButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DecreaseSwrButton, ui_event_DecreaseSwrButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IncreaseSMeterButton, ui_event_IncreaseSMeterButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DecreaseSMeterButton, ui_event_DecreaseSMeterButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SplitButton, ui_event_SplitButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NrButton, ui_event_NrButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NbButton, ui_event_NbButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DebugMode, ui_event_DebugMode, LV_EVENT_ALL, NULL);

}
