// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: Sunton_SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_SignalPanel;
extern lv_obj_t * ui_SMeterSegmentsContainer; // Container for S-Meter segments
extern lv_obj_t * ui_SMeterSegments[30];     // Array for 30 S-Meter segments
extern lv_obj_t * ui_SMeterLabelsContainer; // Container for S-Meter tick labels
extern lv_obj_t * ui_SMeterTickLabels[8]; // Array for 8 S-Meter tick labels
extern lv_obj_t * ui_SMeterLabel;
extern void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_SwrMeterLabel;
extern lv_obj_t * ui_SwrMeterSegmentsContainer; // Container for SWR segments
extern lv_obj_t * ui_SwrMeterSegments[30];     // Array for 30 SWR segments
extern lv_obj_t * ui_SwrTextLabel;
extern lv_obj_t * ui_AlcMeterSegmentsContainer; // Container for ALC segments
extern lv_obj_t * ui_AlcMeterSegments[30];     // Array for 30 ALC segments (single mode)
extern lv_obj_t * ui_ALC;
extern lv_obj_t * ui_CompMeterSegmentsContainer; // Container for COMP segments
extern lv_obj_t * ui_CompMeterSegments[15];     // Array for 15 COMP segments (dual mode)
extern lv_obj_t * ui_CompLabel;
extern lv_obj_t * ui_AfGainBar;
extern lv_obj_t * ui_AfGainLabel;
extern lv_obj_t * ui_RfGainLabel;
extern lv_obj_t * ui_RfGainBar;
extern lv_obj_t * ui_VfoAValue;
extern lv_obj_t * ui_VfoAFreqContainer;  // Container for segmented frequency display
extern lv_obj_t * ui_VfoAFreqMHz;        // MHz segment (e.g., "14")
extern lv_obj_t * ui_VfoAFreqKHz;        // kHz segment (e.g., "012") 
extern lv_obj_t * ui_VfoAFreqHz;         // Hz segment (e.g., "000")
extern lv_obj_t * ui_VfoAFreqDot1;       // First period separator "."
extern lv_obj_t * ui_VfoAFreqDot2;       // Second period separator "."
extern lv_obj_t * ui_ModeLabel;
extern lv_obj_t * ui_DataModeLabel;
extern lv_obj_t * ui_VfoBValue;
extern lv_obj_t * ui_VfoAButtonBackground;
extern lv_obj_t * ui_VfoALabel;
extern lv_obj_t * ui_VfoBButtonBackground;
extern lv_obj_t * ui_VfoBLabel;
extern lv_obj_t * ui_MemoryLabel;           // Shows "M" when in memory mode
extern lv_obj_t * ui_MemoryChannelLabel;    // Shows "M.CH XX" when in memory mode
extern void ui_event_changeAntenna(lv_event_t * e);
extern lv_obj_t * ui_AntButton;
extern lv_obj_t * ui_Ant1Label;
extern lv_obj_t * ui_Ant2Label;
extern void ui_event_UtcTime(lv_event_t * e);
extern lv_obj_t * ui_UtcTime;
extern void update_filter_visibility_from_dropdown_idx(uint16_t dropdown_idx);
extern int s_current_radio_mode;
extern lv_obj_t * ui_PwrLabel;
extern lv_obj_t * ui_PwrValueLabel;
extern void ui_event_IfFilter(lv_event_t * e);
extern lv_obj_t * ui_IfFilter;
extern lv_obj_t * ui_IfFilterALabel;
extern lv_obj_t * ui_IfFilterBLabel;
// Function to update filter display from CAT parser
extern void ui_screen1_update_filter(int filter_value);
extern void ui_event_RxTxLabel(lv_event_t * e);
extern lv_obj_t * ui_RxTxLabel;
extern void ui_event_PreAmpButton(lv_event_t * e);
extern lv_obj_t * ui_PreAmpButton;
extern lv_obj_t * ui_PreAmpButtonLabel;
extern void ui_event_AttButton(lv_event_t * e);
extern lv_obj_t * ui_AttButton;
extern lv_obj_t * ui_AttButtonLabel;
extern void ui_event_AtTuneButton(lv_event_t * e);
extern lv_obj_t * ui_AtTuneButton;
extern lv_obj_t * ui_AtTuneButtonLabel;
extern void ui_event_ProcButton(lv_event_t * e);
extern lv_obj_t * ui_ProcButton;
extern lv_obj_t * ui_ProcButtonLabel;
extern void ui_event_IncreaseSwrButton(lv_event_t * e);
extern lv_obj_t * ui_IncreaseSwrButton;
extern void ui_event_IncreaseSwrLabel(lv_event_t * e);
extern lv_obj_t * ui_IncreaseSwrLabel;
extern void ui_event_DecreaseSwrButton(lv_event_t * e);
extern lv_obj_t * ui_DecreaseSwrButton;
extern lv_obj_t * ui_DecreaseSwrLabel;
extern void ui_event_IncreaseSMeterButton(lv_event_t * e);
extern lv_obj_t * ui_IncreaseSMeterButton;
extern lv_obj_t * ui_IncreaseSMeterLabel;
extern void ui_event_DecreaseSMeterButton(lv_event_t * e);
extern lv_obj_t * ui_DecreaseSMeterButton;
extern lv_obj_t * ui_DecreaseSMeterLabel;
extern void ui_event_SplitButton(lv_event_t * e);
extern lv_obj_t * ui_SplitButton;
extern lv_obj_t * ui_SplitButtonLabel;
extern void ui_event_NrButton(lv_event_t * e);
extern lv_obj_t * ui_NrButton;
extern lv_obj_t * ui_NrButtonLabel;
extern lv_obj_t * ui_XvtrLabel;
extern lv_obj_t * ui_AgcLabel;
extern lv_obj_t * ui_NotchLabel;
extern lv_obj_t * ui_RitContainer;
extern lv_obj_t * ui_RitLabel;
extern lv_obj_t * ui_RitValue;
extern lv_obj_t * ui_XitContainer;
extern lv_obj_t * ui_XitLabel;
extern lv_obj_t * ui_XitValue;
extern lv_obj_t * ui_PwrSwitch;
extern lv_obj_t * ui_OnOffLabel;
extern void ui_event_NbButton(lv_event_t * e);
extern lv_obj_t * ui_NbButton;
extern lv_obj_t * ui_NbButtonLabel;
extern void ui_event_DebugMode(lv_event_t * e);
extern lv_obj_t * ui_DebugMode;
extern lv_obj_t * ui_DebugModeButtonLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

