// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Sunton_SquareLine_Project

#include <stdio.h>
#include <time.h>
#include "ui.h"
#include "esp_log.h"
#include "esp_err.h"
#include "esp_timer.h"
#include "ui_helpers.h"
#include "widgets/lv_textarea.h"
#include "freertos/projdefs.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "lvgl.h"
#include "ui.h"
#include "ui_helpers.h"
#include "ntp_client.h"  // Include this if you need to reference NTP client functions


#define TAG "UI"
static void ui_time_update_task(void *pvParameters);
int64_t last_update = 0;


///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_SignalPanel;
lv_obj_t * ui_SMeterBar;
lv_obj_t * ui_SMeterLabel;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
lv_obj_t * ui_SwrMeterLabel;
lv_obj_t * ui_SwrMeterBar;
lv_obj_t * ui_SwrTextLabel;
lv_obj_t * ui_SignalStrengthLabel;
lv_obj_t * ui_AlcMeterBar;
lv_obj_t * ui_ALC;
lv_obj_t * ui_AfGainBar;
lv_obj_t * ui_AfGainLabel;
lv_obj_t * ui_RfGainLabel;
lv_obj_t * ui_RfGainBar;
lv_obj_t * ui_VfoAValue;
void ui_event_ModeDropDown(lv_event_t * e);
lv_obj_t * ui_ModeDropDown;
lv_obj_t * ui_VfoBValue;
lv_obj_t * ui_VfoAButtonBackground;
lv_obj_t * ui_VfoALabel;
lv_obj_t * ui_VfoBButtonBackground;
lv_obj_t * ui_VfoBLabel;
void ui_event_AntButton(lv_event_t * e);
lv_obj_t * ui_AntButton;
lv_obj_t * ui_Ant1Label;
lv_obj_t * ui_Ant2Label;
void ui_event_UtcTime(lv_event_t * e);
lv_obj_t * ui_UtcTime;
lv_obj_t * ui_PwrLabel;
lv_obj_t * ui_PwrValueLabel;
void ui_event_IfFilter(lv_event_t * e);
lv_obj_t * ui_IfFilter;
lv_obj_t * ui_IfFilterALabel;
lv_obj_t * ui_IfFilterBLabel;
void ui_event_RxTxLabel(lv_event_t * e);
lv_obj_t * ui_RxTxLabel;
void ui_event_PreAmpButton(lv_event_t * e);
lv_obj_t * ui_PreAmpButton;
lv_obj_t * ui_PreAmpButtonLabel;
void ui_event_AttButton(lv_event_t * e);
lv_obj_t * ui_AttButton;
lv_obj_t * ui_AttButtonLabel;
void ui_event_AtTuneButton(lv_event_t * e);
lv_obj_t * ui_AtTuneButton;
lv_obj_t * ui_AtTuneButtonLabel;
void ui_event_ProcButton(lv_event_t * e);
lv_obj_t * ui_ProcButton;
lv_obj_t * ui_ProcButtonLabel;
void ui_event_IncreaseSwrButton(lv_event_t * e);
lv_obj_t * ui_IncreaseSwrButton;
void ui_event_IncreaseSwrLabel(lv_event_t * e);
lv_obj_t * ui_IncreaseSwrLabel;
void ui_event_DecreaseSwrButton(lv_event_t * e);
lv_obj_t * ui_DecreaseSwrButton;
lv_obj_t * ui_DecreaseSwrLabel;
void ui_event_IncreaseSMeterButton(lv_event_t * e);
lv_obj_t * ui_IncreaseSMeterButton;
lv_obj_t * ui_IncreaseSMeterLabel;
void ui_event_DecreaseSMeterButton(lv_event_t * e);
lv_obj_t * ui_DecreaseSMeterButton;
lv_obj_t * ui_DecreaseSMeterLabel;
void ui_event_SplitButton(lv_event_t * e);
lv_obj_t * ui_SplitButton;
lv_obj_t * ui_SplitButtonLabel;
void ui_event_NrButton(lv_event_t * e);
lv_obj_t * ui_NrButton;
lv_obj_t * ui_NrButtonLabel;
lv_obj_t * ui_AgcLabel;
lv_obj_t * ui_RitLabel;
lv_obj_t * ui_RitValue;
lv_obj_t * ui_XitLabel;
lv_obj_t * ui_RitValue1;
lv_obj_t * ui_PwrSwitch;
lv_obj_t * ui_OnOffLabel;
void ui_event_NbButton(lv_event_t * e);
lv_obj_t * ui_NbButton;
lv_obj_t * ui_NbButtonLabel;
void ui_event_DebugMode(lv_event_t * e);
lv_obj_t * ui_DebugMode;
lv_obj_t * ui_DebugModeButtonLabel;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_TextArea1;
lv_obj_t * ui_DebugLabel;
void ui_event_ReturnToScreen1Button(lv_event_t * e);
lv_obj_t * ui_ReturnToScreen1Button;
lv_obj_t * ui_ReturnToScreen1BtnLabel;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_VfoAButtonBackground, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_VfoBButtonBackground, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_VfoAButtonBackground, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_VfoBButtonBackground, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_ModeDropDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        changeMode(e);
    }
}
void ui_event_AntButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        changeAntenna(e);
        _ui_flag_modify(ui_Ant2Label, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Ant1Label, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_UtcTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    // lv_textarea_set_text(ui_UtcTime, e->user_data);
}
void ui_event_IfFilter(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        changeFilter(e);
        _ui_flag_modify(ui_IfFilterALabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_IfFilterBLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_RxTxLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_checked_set_text_value(ui_RxTxLabel, target, "RX", "TX");
        _ui_state_modify(ui_RxTxLabel, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        _ui_flag_modify(ui_SignalStrengthLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_PwrValueLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_SMeterLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_PwrLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_PreAmpButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        TogglePreAmp(e);
    }
}
void ui_event_AttButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        TogglePreAmp(e);
    }
}
void ui_event_AtTuneButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        AtTune(e);
    }
}
void ui_event_ProcButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        TogglePreAmp(e);
    }
}
void ui_event_IncreaseSwrButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_bar_increment(ui_SwrMeterBar, 5, LV_ANIM_ON);
    }
}
void ui_event_IncreaseSwrLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_bar_increment(ui_SwrMeterBar, 50, LV_ANIM_ON);
    }
}
void ui_event_DecreaseSwrButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_bar_increment(ui_SwrMeterBar, -5, LV_ANIM_ON);
    }
}
void ui_event_IncreaseSMeterButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_bar_increment(ui_SMeterBar, 5, LV_ANIM_ON);
    }
}
void ui_event_DecreaseSMeterButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_bar_increment(ui_SMeterBar, -5, LV_ANIM_ON);
    }
}
void ui_event_SplitButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        TogglePreAmp(e);
    }
}
void ui_event_NrButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        TogglePreAmp(e);
    }
}
void ui_event_NbButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        TogglePreAmp(e);
    }
}
void ui_event_DebugMode(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_bar_increment(ui_SwrMeterBar, 5, LV_ANIM_ON);
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_ReturnToScreen1Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init()
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);

    xTaskCreate(ui_time_update_task, "ui_time_update", 4096, NULL, 1, NULL);
    ESP_LOGI(TAG, "Creating ui_time_update_task");
}

void ui_time_update_task(void *pvParameters)  {
    struct tm timeinfo;
    time_t now;
    char time_str[64];
    ESP_LOGI(TAG, "ui_time_update_task(): attempting to set time");
    lv_label_set_long_mode(ui_UtcTime, LV_LABEL_LONG_CLIP);

    while (1) {
        time(&now);
        localtime_r(&now, &timeinfo);
        strftime(time_str, sizeof(time_str), "%H:%M:%S", &timeinfo);

        lv_label_set_text_fmt(ui_UtcTime, time_str, "%H:%M:%S");
        // ESP_LOGI(TAG, "Received queue with new time: %02d:%02d:%02d", timeinfo.tm_hour, timeinfo.tm_min, timeinfo.tm_sec);

        int64_t current_time = esp_timer_get_time();
        int64_t time_to_wait = 1000000 - (current_time - last_update) % 1000000;
        vTaskDelay(pdMS_TO_TICKS(time_to_wait / 1000));
        last_update = current_time + time_to_wait;
    }
}