// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: Sunton_SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "esp_lvgl_port.h"   // For lvgl_port_lock/unlock
#include "esp_log.h"         // For ESP_LOGE

static const char *TAG_UI = "UI_INIT"; // Tag for logging

///////////////////// VARIABLES ////////////////////
lv_anim_t * test_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
lv_anim_t * test_Animation(lv_obj_t * TargetObject, int delay)
{
    lv_anim_t * out_anim = 0;

    return out_anim;
}

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    if (lvgl_port_lock(5000)) {  // 5 second timeout for UI init
        lv_display_t * dispp = lv_display_get_default();
        lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                                   true, LV_FONT_DEFAULT);
        lv_display_set_theme(dispp, theme);
        ui_Screen1_screen_init();
        // Pre-create Settings screen to avoid heavy creation during event handling
        // This prevents long-running UI builds inside lv_timer_handler that can starve IDLE tasks.
        ui_Screen2_screen_init();
        // Initial actions container (kept for compatibility)
        ui____initial_actions0 = lv_obj_create(NULL);
        lv_screen_load(ui_Screen1);

        lvgl_port_unlock();
    } else {
        ESP_LOGE(TAG_UI, "Failed to take LVGL mutex in ui_init!");
        // Handle critical error: UI cannot be initialized safely.
    }
}

void ui_destroy(void)
{
    if (lvgl_port_lock(5000)) {  // 5 second timeout for UI destroy
        ui_Screen1_screen_destroy();
        ui_Screen2_screen_destroy();
        // If ui____initial_actions0 needs explicit deletion and is an LVGL object:
        // if (ui____initial_actions0) {
        //     lv_obj_delete(ui____initial_actions0);
        //     ui____initial_actions0 = NULL;
        // }
        lvgl_port_unlock();
    } else {
        ESP_LOGE(TAG_UI, "Failed to take LVGL mutex in ui_destroy!");
    }
}
