// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: Sunton_SquareLine_Project

#ifndef _SUNTON_SQUARELINE_PROJECT_UI_H
#define _SUNTON_SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../managed_components/lvgl__lvgl/lvgl.h"
#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_SignalPanel;
extern lv_obj_t *ui_SMeterBar;
extern lv_obj_t *ui_SMeterLabel;
void ui_event_Switch1( lv_event_t * e);
extern lv_obj_t *ui_Switch1;
extern lv_obj_t *ui_SwrMeterLabel;
extern lv_obj_t *ui_SwrMeterBar;
extern lv_obj_t *ui_SwrTextLabel;
extern lv_obj_t *ui_SignalStrengthLabel;
extern lv_obj_t *ui_ALC;
extern lv_obj_t *ui_AfGainBar;
extern lv_obj_t *ui_AfGainLabel;
extern lv_obj_t *ui_RfGainLabel;
extern lv_obj_t *ui_RfGainBar;
extern lv_obj_t *ui_VfoAValue;
void ui_event_ModeDropDown( lv_event_t * e);
extern lv_obj_t *ui_ModeDropDown;
extern lv_obj_t *ui_VfoBValue;
extern lv_obj_t *ui_VfoAuttonBackground;
extern lv_obj_t *ui_VfoALabel;
extern lv_obj_t *ui_VfoBButtonBackground;
extern lv_obj_t *ui_VfoBLabel;
void ui_event_AntButton( lv_event_t * e);
extern lv_obj_t *ui_AntButton;
extern lv_obj_t *ui_Ant1Label;
extern lv_obj_t *ui_Ant2Label;
extern lv_obj_t *ui_UtcTime;
void ui_event_IfFilter( lv_event_t * e);
extern lv_obj_t *ui_IfFilter;
extern lv_obj_t *ui_IfFilterALabel;
extern lv_obj_t *ui_IfFilterBLabel;
extern lv_obj_t *ui_PwrValueLabel2;
extern lv_obj_t *ui_PwrValueLabel;
extern lv_obj_t *ui_PwrLabel;
void ui_event_RxTxLabel( lv_event_t * e);
extern lv_obj_t *ui_RxTxLabel;
extern lv_obj_t *ui_SplitLabel;
void ui_event_PreAmpButton( lv_event_t * e);
extern lv_obj_t *ui_PreAmpButton;
extern lv_obj_t *ui_PreAmpButtonLabel;
void ui_event_AttButton( lv_event_t * e);
extern lv_obj_t *ui_AttButton;
extern lv_obj_t *ui_AttButtonLabel;
void ui_event_AtTuneButton( lv_event_t * e);
extern lv_obj_t *ui_AtTuneButton;
extern lv_obj_t *ui_AtTuneButtonLabel;
void ui_event_ProcButton( lv_event_t * e);
extern lv_obj_t *ui_ProcButton;
extern lv_obj_t *ui_ProcButtonLabel;
// SCREEN: ui_Screen2
// void ui_Screen2_screen_init(void);
// extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
