// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: Sunton_SquareLine_Project

#ifndef _SUNTON_SQUARELINE_PROJECT_UI_H
#define _SUNTON_SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * test_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_Font16);
LV_FONT_DECLARE(ui_font_Font18);
LV_FONT_DECLARE(ui_font_Font30);
LV_FONT_DECLARE(ui_font_Font48);
LV_FONT_DECLARE(ui_font_Frequency);
LV_FONT_DECLARE(ui_font_MeterFont);
LV_FONT_DECLARE(ui_font_UTCTime);
LV_FONT_DECLARE(ui_font_FrequencyFont);
LV_FONT_DECLARE(ui_font_FrequencyFontSmall);
LV_FONT_DECLARE(ui_font_ButtonFont);
LV_FONT_DECLARE(ui_font_ButtonFontLargeBold);
LV_FONT_DECLARE(ui_font_ButtonFontSmallMedium);
LV_FONT_DECLARE(ui_font_ButtonSmallRegular);
LV_FONT_DECLARE(ui_font_Glyphs24);
LV_FONT_DECLARE(ui_font_Glyphs30);
LV_FONT_DECLARE(ui_font_Glyphs58);
LV_FONT_DECLARE(ui_font_Glyphs70);

// UI INIT
void ui_init(void);
void ui_destroy(void);

// ULTRA-FAST VFO UPDATE SUPPORT
// Exposed for direct CAT parser access to bypass messaging overhead
extern lv_obj_t *ui_VfoAFreqMHz;
extern lv_obj_t *ui_VfoAFreqKHz;
extern lv_obj_t *ui_VfoAFreqHz;
extern lv_obj_t *ui_VfoBValue;
extern lv_obj_t *ui_VfoAFreqContainer;

// Frequency string cache for ultra-fast updates
extern const char* g_khz_cache[1000];
extern const char* g_hz_cache[1000];
extern const char* g_mhz_cache[1000];
extern bool g_freq_cache_initialized;

// Function to initialize frequency cache from CAT parser
void init_freq_cache_extern(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
