// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: Sunton_SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void changeMode(lv_event_t * e);
void changeAntenna(lv_event_t * e);
void changeFilter(lv_event_t * e);
void TogglePreAmp(lv_event_t * e);
void AtTune(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
