// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: Sunton_SquareLine_Project

#include "ui.h"

void changeMode(lv_event_t * e)
{
	// Your code here
}

void changeAntenna(lv_event_t * e)
{
	// Your code here
}

void changeFilter(lv_event_t * e)
{
	// Your code here
}

void TogglePreAmp(lv_event_t * e)
{
	// Your code here
}

void AtTune(lv_event_t * e)
{
	// Your code here
}
