// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Sunton_SquareLine_Project

#include "ui.h"
#include "uart.h"
#include "esp_log.h"

// External variables and functions from ui_Screen1.c
extern int s_current_radio_mode;

void changeMode(lv_event_t * e)
{
    lv_obj_t * target = (lv_obj_t*)lv_event_get_target(e);
    if (!lv_obj_is_valid(target)) {
        return;
    }
    
    uint32_t dropdown_idx = lv_dropdown_get_selected(target);
    
    // Map dropdown index to CAT command and send it
    // Dropdown options: "USB\nLSB\nCW\nDATA\nFM\nAM" (indices 0-5)
    const char* mode_commands[] = {
        "MD2;", // USB
        "MD1;", // LSB  
        "MD3;", // CW
        "MD9;", // DATA
        "MD4;", // FM
        "MD5;"  // AM
    };
    
    if (dropdown_idx < 6) {
        // Send the mode command to radio
        uart_write_message(mode_commands[dropdown_idx]);
        
        // Update s_current_radio_mode for immediate UI consistency
        switch (dropdown_idx) {
            case 0: s_current_radio_mode = 2; break; // USB
            case 1: s_current_radio_mode = 1; break; // LSB
            case 2: s_current_radio_mode = 3; break; // CW
            case 3: s_current_radio_mode = 9; break; // DATA
            case 4: s_current_radio_mode = 4; break; // FM
            case 5: s_current_radio_mode = 5; break; // AM
            default: s_current_radio_mode = -1; break;
        }
        
        // Update filter visibility immediately without waiting for CAT response
        update_filter_visibility_from_dropdown_idx(dropdown_idx);
        
        ESP_LOGI("UI_EVENTS", "Mode changed to index %u (CAT mode %d)", dropdown_idx, s_current_radio_mode);
    }
}

// Global to track current antenna state (mirrors CAT parser state)
static int g_ui_current_antenna = 0; // 0=ANT1, 1=ANT2

void changeAntenna(lv_event_t * e)
{
	// Toggle between ANT1 (0) and ANT2 (1)
	// The AN command format is: ANP1P2P3;
	// P1: 0=ANT1, 1=ANT2
	// P2: RX antenna usage (9=no change)
	// P3: Drive output (9=no change)

	// Toggle antenna select
	g_ui_current_antenna = (g_ui_current_antenna == 0) ? 1 : 0;

	// Send AN command: toggle antenna, keep other params unchanged
	const char* cmd = (g_ui_current_antenna == 0) ? "AN099;" : "AN199;";

	esp_err_t ret = uart_write_message(cmd);
	if (ret == ESP_OK) {
		ESP_LOGI("UI_EVENTS", "Antenna toggle sent: %s (ANT%d)", cmd, g_ui_current_antenna + 1);
	} else {
		ESP_LOGE("UI_EVENTS", "Failed to send antenna command: %s", esp_err_to_name(ret));
		// Revert toggle on failure
		g_ui_current_antenna = (g_ui_current_antenna == 0) ? 1 : 0;
	}
}

void setUtcTime(lv_event_t * e)
{
	// Your code here
}

void changeFilter(lv_event_t * e)
{
	// Your code here
}

void TogglePreAmp(lv_event_t * e)
{
	// Your code here
}

void AtTune(lv_event_t * e)
{
	// Your code here
}
